### PR TITLE
Feature/sca adc backport

### PR DESCRIPTION
**Pull request by mexanick**
Backporting Ram's development to the `release/v1.1.X` branch
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Required to read out various temperature sensors on the detector
## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by lpetre-ulb** [comment]
As discussed during yesterday DAQ meeting there are changes on the SCA ADC input mapping, so it might be best to wait until the `feature/sca-interface` branch is patched. I'll open an issue with the list of changes so someone wan work on it.

**Comment by mexanick** [comment]
@lpetre-ulb I can implement the required changes if you supply me the correct inputs mapping

**Comment by lpetre-ulb** [comment]
> @lpetre-ulb I can implement the required changes if you supply me the correct inputs mapping

@mexanick, I listed the changes made to the OH in [this issue](https://github.com/cms-gem-daq-project/ctp7_modules/issues/138). Please let me know if something is unclear.

**Review by bdorney — DISMISSED** [review]
Seems a pretty straightforward backport by applying the previously approved commits.

**Comment by bdorney** [comment]
`rebase` needed.

**Comment by mexanick** [comment]
rebased

**Review by jsturdy — APPROVED** [review]

**Pull request merged**
