### PR TITLE
New Feature: Set Channel Registers

### PR DESCRIPTION
**Pull request by bdorney**
## Description

Addresses: https://github.com/cms-gem-daq-project/ctp7_modules/issues/14

New RPC method for setting channel registers `setChannelRegistersVFAT3Local(...)`.  Here's a snap shot of the `doxygen` documentation:

```
*! \fn void setChannelRegistersVFAT3Local(localArgs * la, uint32_t ohN, uint32_t vfatMask, uint32_t *calEnable, uint32_t *masks, uint32_t *trimARM, uint32_t *trimARMPol, uint32_t *trimZCC, uint32_t *trimZCCPol);                          
 *  \brief writes all vfat3 channel registers from AMC
 *  \param ohN Optohybrid optical link number
 *  \param vfatMask Bitmask of chip positions determining which chips to use
 *  \param calEnable array pointer for calEnable with 3072 entries, the (vfat,chan) pairing determines the array index via: idx = vfat*128 + chan
 *  \param masks as calEnable but for channel masks
 *  \param trimARM as calEnable but for arming comparator trim value
 *  \param trimARMPol as calEnable but for arming comparator trim polarity
 *  \param trimZCC as calEnable but for zero crossing comparator trim value
 *  \param trimZCCPol as calEnable but for zero crossing comparator trim polarity
 */
void setChannelRegistersVFAT3Local(localArgs * la, uint32_t ohN, uint32_t vfatMask, uint32_t *calEnable, uint32_t *masks, uint32_t *trimARM, uint32_t *trimARMPol, uint32_t *trimZCC, uint32_t *trimZCCPol)
```

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

For trimming VFAT3 need to write between 3-6 channel registers per channel per VFAT.  So it's not feasible for the host machine to do this; the CTP7 should do this.

## How Has This Been Tested?

Tested when trimming VFAT3, was able to achieve the following:

vfat0_pruned_summary_untrimmed
vfat0_pruned_summary_trimmed

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by mexanick — CHANGES_REQUESTED** [review]
the files inlcude/vfat3.h and src/vfat3.cpp has been changed since in pervious PR. Thus, the PR has to be rebased. Also the documentation should only go in one file (if the header exists, it should go there)

**Comment by bdorney** [comment]
> the files inlcude/vfat3.h and src/vfat3.cpp has been changed since in pervious PR. Thus, the PR has to be rebased. Also the documentation should only go in one file (if the header exists, it should go there)

Ah okay, ignorance on my part.  I'll remove the documentation from the `*.cpp` file and rebase this PR once #29 is merged.

**Comment by mexanick** [comment]
You can go for rebase now, I'll wait for a new commit/pr notification

**Comment by bdorney** [comment]
superceded by https://github.com/cms-gem-daq-project/ctp7_modules/pull/37

**Pull request closed without merging**
