### PR TITLE
Updating master to the legacy version of develop 

### PR DESCRIPTION
**Pull request by mexanick**
Target legacy release off of master branch
## Description

Multiple changes, tested on various test stands. No additional testing is required, but PR needs a review

### CODE REVIEW

**Review by jsturdy — DISMISSED** [review]

**Comment by lpetre-ulb** [comment]
I think there is one bug left in the DAC scans with the updated registers. I haven't had the time to prepare a full issue and PR, but I already pushed a commit fixing the issue in a personal branch : https://github.com/lpetre-ulb/ctp7_modules/commit/92025285e3f096d409cd219e61e898291453fc64 It also works steadily on `eagle64` since the noise measurements we (Gilles, Elizabeth and I) tried to do before the Christmas break : http://cmsonline.cern.ch/cms-elog/1077967

I was planning to write a proper GitHub issue and PR this afternoon once I will have updated the CTP7 firmware at ULB.

**Comment by jsturdy** [comment]
> I was planning to write a proper GitHub issue and PR this afternoon once I will have updated the CTP7 firmware at ULB.

Definitely start with the issue, as per my [comment](https://github.com/lpetre-ulb/ctp7_modules/commit/92025285e3f096d409cd219e61e898291453fc64#r31973225) on your change

**Comment by bdorney** [comment]
> I think there is one bug left in the DAC scans with the updated registers. I haven't had the time to prepare a full issue and PR, but I already pushed a commit fixing the issue in a personal branch : [lpetre-ulb@9202528](https://github.com/lpetre-ulb/ctp7_modules/commit/92025285e3f096d409cd219e61e898291453fc64) It also works steadily on `eagle64` since the noise measurements we (Gilles, Elizabeth and I) tried to do before the Christmas break : http://cmsonline.cern.ch/cms-elog/1077967
> 
> I was planning to write a proper GitHub issue and PR this afternoon once I will have updated the CTP7 firmware at ULB.

Is this beyond what is attempted to be addressed in the WIP PR [here](https://github.com/cms-gem-daq-project/ctp7_modules/pull/76)?

**Comment by lpetre-ulb** [comment]
> > I was planning to write a proper GitHub issue and PR this afternoon once I will have updated the CTP7 firmware at ULB.
> 
> Definitely start with the issue, as per my [comment](https://github.com/lpetre-ulb/ctp7_modules/commit/92025285e3f096d409cd219e61e898291453fc64#r31973225) on your change

I filled the issue here : https://github.com/cms-gem-daq-project/ctp7_modules/issues/80

> Is this beyond what is attempted to be addressed in the WIP PR [here](https://github.com/cms-gem-daq-project/ctp7_modules/pull/76)?

I think it is since `readVFAT3ADCLocal(...)` is never called in `calibration_routines.cpp`

**Comment by bdorney** [comment]
I think we should wait for this update until #80 is resolved.  However if #77 turns out to be ahead of #80 then we should merge this (#79) PR and then hot fix master after the fact.

**Comment by jsturdy** [comment]
@mexanick, @bdorney, #81 is merged, anything still outstanding?

**Comment by bdorney** [comment]
> @mexanick, @bdorney, #81 is merged, anything still outstanding?

I think only #76 but I haven't had time to come back to that as of yet.  The implementation in #76 while potentially not optimal is functional.

**Comment by jsturdy** [comment]
> > @mexanick, @bdorney, #81 is merged, anything still outstanding?
> 
> I think only #76 but I haven't had time to come back to that as of yet. The implementation in #76 while potentially not optimal is functional.

OK, so then I think that can be considered a "development" and can just be rebased off the updated tree following this merge

**Comment by bdorney** [comment]
> > > @mexanick, @bdorney, #81 is merged, anything still outstanding?
> > 
> > 
> > I think only #76 but I haven't had time to come back to that as of yet. The implementation in #76 while potentially not optimal is functional.
> 
> OK, so then I think that can be considered a "development" and can just be rebased off the updated tree following this merge

Sounds good with me.

**Review by bdorney — APPROVED** [review]

**Pull request merged**
